name: github pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.95.0'

      - name: Build
        run: hugo --minify

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: publish
        uses: actions/deploy-pages@v4
